version: '3'

services:
  reverse-proxy:
    image: traefik:v2.4
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.letsencrypt.acme.email=lingyong.sun@gmail.com"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro
  swarmpit:
    image: swarmpit/install:edge
    environment:
      INTERACTIVE: 0
      STACK_NAME: controller
      APP_PORT: 80
    labels:
      traefik.enable: true
      traefik.http.routers.swarmpit.entrypoints: web
      traefik.http.routers.swarmpit.rule: Host(`swarm.lysz210.name`)
      traefik.http.middlewares.https-redirect.redirectscheme.scheme: https
      # traefik.http.middlewares.https-redirect.redirectscheme.permanent: true
      traefik.http.routers.swarmpit.middlewares: https-redirect@docker
      traefik.http.routers.swarmpit-s.rule: Host(`swarm.lysz210.name`)
      traefik.http.routers.swarmpit-s.entrypoints: websecure
      traefik.http.routers.swarmpit-s.tls.certresolver: letsencrypt
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
