version: "3.7"

services:
  reverse-proxy:
    image: traefik:v2.4
    deploy:
      labels:
        traefik.enable: "true"
        traefik.constraint-label: traefiknet
        traefik.http.middlewares.admin-auth.basicauth.users: ${USERNAME?Variable not set}:${HASHED_PASSWORD?Variable not set}
        traefik.http.middlewares.https-redirect.redirectscheme.scheme: https

        # traefik-http set up only to use the middleware to redirect to https
        # Uses the environment variable DOMAIN
        traefik.http.routers.traefik-public-http.rule: Host(`${DOMAIN?Variable not set}`)
        traefik.http.routers.traefik-public-http.entrypoints: web
        traefik.http.routers.traefik-public-http.middlewares: https-redirect
        # traefik-https the actual router using HTTPS
        # Uses the environment variable DOMAIN
        traefik.http.routers.traefik-public-https.rule: Host(`${DOMAIN?Variable not set}`)
        traefik.http.routers.traefik-public-https.entrypoints: websecure
        traefik.http.routers.traefik-public-https.tls: "true"
        # Use the special Traefik service api@internal with the web UI/Dashboard
        traefik.http.routers.traefik-public-https.service: api@internal
        traefik.http.routers.api.tls.certresolver: letsencrypt
        traefik.http.services.traefik-public.loadbalancer.server.port: 8080
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./configs/traefik:/etc/traefik:ro
    networks:
      - traefiknet
