version: "3.7"

networks:
  sail:
    external: true
volumes:
  sailpgsql:
    driver: local
secrets:
  dotenv:
    file: ${WEBSITE_DOTENV}

services:
  website:
    image: lysz210/website
    environment:
      WWWUSER: "${WWWUSER}"
      LARAVEL_SAIL: 1

    secrets:
      - source: dotenv
        target: /var/www/html/.env
    networks:
      - sail
      - traefiknet
    deploy:
      labels:
        traefik.enable: "true"
        traefik.constraint-label: traefiknet
        traefik.http.routers.website.entrypoints: http
        traefik.http.routers.website.rule: Host(`lysz210.name`)
        traefik.http.middlewares.https-redirect.redirectscheme.scheme: https
        #traefik.http.middlewares.https-redirect.redirectscheme.permanent: true
        traefik.http.routers.website-s.rule: Host(`lysz210.name`)
        traefik.http.routers.website-s.entrypoints: https
        traefik.http.routers.website-s.tls.certresolver: le
        traefik.http.routers.traefik-public-https.tls: "true"
        traefik.http.services.website.loadbalancer.server.port: 80
  pgsql:
    image: "postgres:13"
    ports:
      - "${FORWARD_DB_PORT:-5432}:5432"
    environment:
      PGPASSWORD: "${DB_PASSWORD:-secret}"
      POSTGRES_DB: "${DB_DATABASE}"
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_PASSWORD: "${DB_PASSWORD:-secret}"
    volumes:
      - "sailpgsql:/var/lib/postgresql/data"
    networks:
      - sail
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-q",
          "-d",
          "${DB_DATABASE}",
          "-U",
          "${DB_USERNAME}",
        ]
      retries: 3
      timeout: 5s
  memcached:
    image: "memcached:alpine"
    ports:
      - "11211:11211"
    networks:
      - sail
