version: '3'

services:
        whoami:
                image: traefik/whoami
                labels:
                        traefik.enable: "true"
                        traefik.http.routers.whoami.entrypoints: web
                        traefik.http.routers.whoami.rule: Host(`swarm.lysz210.name`)
                        traefik.http.middlewares.https-redirect.redirectscheme.scheme: https
                        #traefik.http.middlewares.https-redirect.redirectscheme.permanent: true
                        traefik.http.routers.whoami.middlewares: https-redirect@docker
                        traefik.http.routers.whoami-s.rule: Host(`swarm.lysz210.name`)
                        traefik.http.routers.whoami-s.entrypoints: websecure
                        traefik.http.routers.whoami-s.tls.certresolver: letsencrypt
