providers:
  docker:
    exposedByDefault: false
    swarmMode: true
    network: traefiknet
    constraints: Label(`traefik.constraint-label`, `traefiknet`)

certificatesResolvers:
  letsencrypt:
    acme:
      tlsChallenge: {}
      email: lingyong.sun@gmail.com
      storage: /letsencrypt/acme.json

entryPoints:
  web:
    address: :80
  websecure:
    address: :443

api:
  dashboard: true

log:
  level: DEBUG
