providers:
  docker:
    exposedByDefault: false
    swarmMode: true
    network: traefiknet
    constraints: Label(`traefik.constraint-label`, `traefiknet`)
  file:
    directory: /etc/traefik
    watch: true

certificatesResolvers:
  le:
    acme:
      tlsChallenge: {}
      email: lingyong.sun@gmail.com
      storage: /letsencrypt/acme.json

entryPoints:
  http:
    address: :80
  https:
    address: :443

api:
  dashboard: true
  insecure: true

log:
  level: ERROR

